DROP TABLE IF EXISTS ARRAY_CONTAIN_VAR;
DROP TABLE IF EXISTS OPERAND;
DROP TABLE IF EXISTS STATEMENT;
DROP TABLE IF EXISTS IDENTIFIER;
DROP TABLE IF EXISTS STATEMENT_TYPE;
DROP TABLE IF EXISTS IDENTIFIER_TYPE;

CREATE TABLE IF NOT EXISTS IDENTIFIER_TYPE (
  ITID NUMBER(1) PRIMARY KEY,
  TYPE_NAME VARCHAR2(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS STATEMENT_TYPE (
  STID NUMBER(2) PRIMARY KEY,
  TYPE_NAME VARCHAR2(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS IDENTIFIER (
  NAME VARCHAR2(64) PRIMARY KEY,
  SUBTYPE NUMBER(2) NOT NULL,
  VALUE NUMBER(10),
  FOREIGN KEY(SUBTYPE) REFERENCES IDENTIFIER_TYPE(ITID)
);

CREATE TABLE IF NOT EXISTS STATEMENT (
  SID INTEGER PRIMARY KEY AUTOINCREMENT,
  SUBTYPE NUMBER(2) NOT NULL,
  LABEL VARCHAR2(64),
  FOREIGN KEY(LABEL) REFERENCES IDENTIFIER(NAME),
  FOREIGN KEY(SUBTYPE) REFERENCES STATEMENT_TYPE(STID)
);

CREATE TABLE IF NOT EXISTS OPERAND (
  SID NUMBER(3),
  IDENTIFIER_NAME VARCHAR2(64),
  FOREIGN KEY(IDENTIFIER_NAME) REFERENCES IDENTIFIER(NAME),
  PRIMARY KEY(SID, IDENTIFIER_NAME)
);

CREATE TABLE IF NOT EXISTS ARRAY_CONTAIN_VAR (
  CONTAINER_NAME VARCHAR2(64),
  ELEMENT_NAME VARCHAR2(64),
  ELEMENT_INDEX NUMBER(2) NOT NULL,
  FOREIGN KEY(CONTAINER_NAME) REFERENCES IDENTIFIER(NAME),
  FOREIGN KEY(ELEMENT_NAME) REFERENCES IDENTIFIER(NAME),
  PRIMARY KEY(CONTAINER_NAME, ELEMENT_NAME),
  CHECK(CONTAINER_NAME != ELEMENT_NAME)
);