CC=g++
CFLAGS= -c -o3
SCAPLDIR=./SCAPL/

# Master Compile
SCAPES:

# SCAPL Compile

Identifier.o: $(SCAPLDIR)Identifier.cc $(SCAPLDIR)Identifier.h
	$(CC) $(CFLAGS) $(SCAPLDIR)Identifier.cc 
# UI Compile

# FS Compile